### ISSUE TITLE
Trying this out, what's your approach?

### ISSUE THREAD

**Issue by nickredmark** [possibilities/next-github-auth#11]
Hey there, cool package!

I tried following the instructions and got the following error (client side)

Cannot read property 'split' of undefined

decorators/InjectGithubAccessToken.js:60:7

I'm probably going to find out the issue, but wanted to write you anyway to ask you what the general approach is, in particular how do you share the session/userId between the client and the server?

**Comment by possibilities** [comment]
Oh, I totally missed this message, sorry! (:

> Cannot read property 'split' of undefined

The issue where split is undefined was patched in the meantime and I moved this to be more of a "library" so it's reusable in other next apps (the example was migrated to the `example/` directory).

> in particular how do you share the session/userId between the client and the server?

In a nutshell the way it works:

* There's a cookie with a github access token stored (only accessible on the server)
* On server side requests we extract the access token and fetches the user injecting both as props. I can vaguely imagine there are some apps that don't want or need the access token to be available on the client at all so that might become opt-in at "decoration time".
* The `PublicPage` and `PrivatePage` decorators do the work to make sure values that are injected on the server side get passed on and injected on client rendered pages

**Comment by possibilities** [comment]
Feel free to close this if it's helpful or add any other questions or thoughts! Peace!

**Comment by possibilities** [comment]
Closing, feel free to re-open (;

**Comment by nickredmark** [comment]
Sorry for not answering before: thanks for the info, it was useful.
